imap_module.settings:
  type: mapping
  label: Variable Settings of imap configuration module
  mapping:
   remote_system_name:
     type: string
   port:
     type: int
   flag:
      type: string
   mailbox:
      type: string
   username:
      type: string
   password:
      type: string

