invoice_entity.settings:
  type: mapping
  label: Variable Settings of My Module
  mapping:
   electronic_bill_consecutive:
     type: string
   debit_note_consecutive:
     type: string
   credit_note_consecutive:
     type: string
   electronic_ticket_consecutive:
     type: string
   consecutive_code:
     type: string
   type_of:
      type: string
